### ISSUE TITLE
Where did "top_heads" come from in src/utils/extract_utils.py?

### ISSUE THREAD

**Issue by HuFY-dev** [ericwtodd/function_vectors#1]
I am assuming that you used _causal mediation_ to identify the attention heads, but do you have dedicated scripts to do that? Thanks in advance for your help!

**Comment by ericwtodd** [comment]
Yes that's right. I think you're referring to the `top_heads` lists in `compute_univeral_function_vector` function. These are pre-computed for convenience and are sorted based on their average indirect effect which was computed across many tasks. 

If you're interested in computing the causal indirect effect for each head on a particular task I would check out `src/compute_indirect_effect.py`, which is a script you can use for identifying important attention heads for a particular task.

**Comment by HuFY-dev** [comment]
Thank you!

**Comment by harisethuram** [comment]
Is there a script to compute this list for a new model?
