### ISSUE TITLE
Computation of top_heads in compute_univeral_function_vector function.

### ISSUE THREAD

**Issue by ST172001** [ericwtodd/function_vectors#10]
I see that in the computation of heads in the file **_src/compute_indirect_effect.py_**,  the dataset is required as input. But in the function **_compute_univeral_function_vector_**, the top_heads are precomputed and hardcoded. So can you please clarify this? Does the top_heads depend on the dataset being used?

Thanks in advance

**Comment by ericwtodd** [comment]
Yes - In our experiments, we computed the indirect effect for many tasks  (by running `src/compute_indirect_effect.py` on individual datasets).  But we found that many of the same heads show up as casually important across a majority of tasks we tested. So the head locations listed in the `compute_universal_function_vector` is a ranking of heads based on their average causal effect over several tasks.

If you want to get a list of heads that's specific to one dataset you can run `src/compute_indirect_effect.py` for the dataset of interest. I'd expect the majority of the heads will end up being the same as the universal heads, but the tail of the distribution will be slightly different per task.

**Comment by stripathy-eightfold** [comment]
Yes thanks a lot Eric

**Comment by stripathy-eightfold** [comment]
Also can you please give a ballpark estimate of the size of the dataset that would suffice to get the approximately correct indirect effect?

**Comment by ST172001** [comment]
yes thanks a lot. Can you please give me a ballpark estimate of the size of the dataset that would suffice to get approximately correct indirect effect of the heads?

**Comment by ericwtodd** [comment]
In our paper we used 25 instances of 10-shot prompts to estimate the indirect effect for each head. This seems to be fairly consistent in the heads that it finds when you repeat this across seeds. This would be a dataset of about 250 pairs.

One way to get away with a smaller dataset requirement is to use less shots. Many tasks that we test can be done reasonably well using prompts with 5 shots or less. For example, GPT-J can get ~100% accuracy on the capitalize task using just 2-shots (See appendix E of the paper for plots), which would let you estimate approximate indirect effects with a dataset of ~50 pairs.
You can also use less instances, but we chose 25 to try and average out effects that may have been query-specific or something like that. Feel free to reopen if you have more questions!
