### ISSUE TITLE
Prepend <|endoftext|> instead of <|begin_of_text|> at the beginning of the prompt? 

### ISSUE THREAD

**Issue by HieuNT91** [ericwtodd/function_vectors#11]
Thank you for publishing the code for a great paper! 
In the fv_demo.ipynb notebook you provide, why do you prepend <|endoftext|> instead of <|begin_of_text|> at the beginning of the prompt?  

Should I not prepend <|begin_of_text|> at the beginning and append <|endoftext|> at the end of the prompt? 

![image](https://github.com/ericwtodd/function_vectors/assets/87244343/10de6c2b-5cdd-40c3-84a2-3f7cf2e8996c)

**Comment by ericwtodd** [comment]
The reason for this is that the `fv_demo.ipynb` shows function vectors being used with GPT-J, and GPT-J uses `'<|endoftext|>'` as its BOS token. If you look at the tokenizer you'll find that the same token `bos_token_id = 50256` `eos_token_id = 50256` is both the BOS and EOS token. (You can check out GPT-J's [config docs here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/gptj/configuration_gptj.py) for more details)

If you're using a different model that doesn't prepend a BOS token, you'll probably have to amend that. However, other models like Llama-2 which use a sentence-piece-based tokenizer will typically prepend the BOS for you and you'll find something like this: (`'<s>'`) at the beginning of prompts.

**Comment by HieuNT91** [comment]
Thank you so much for your fast response!
