### ISSUE TITLE
Performance metric used in the paper

### ISSUE THREAD

**Issue by HieuNT91** [ericwtodd/function_vectors#12]
Hi, Thank you for your great code! 

In the paper, do you use the first-word score or first-token score for your reported accuracy?

**Comment by ericwtodd** [comment]
If an answer is split into multiple tokens, we typically reported the first token score to measure accuracy. (this is mentioned in the paper as part of appendix C which contains experimental details)
For the evaluations on natural text, we measured whether the expected answer appeared within 5 tokens of generation (We used 10 tokens in the case of country-capital).
