### ISSUE TITLE
Could you provide code in Sec 3.2?

### ISSUE THREAD

**Issue by foggy-frost-forest** [ericwtodd/function_vectors#2]
Hello, could you provide code in Sec 3.2 that implement the experiment of Table 6, thank you so much.

**Comment by ericwtodd** [comment]
Hi! Please check out the `src/vocab_reconstruction.py` file. This should have the code for the optimization described in Section 3.2 & that was used to populate Table 6.

**Comment by ericwtodd** [comment]
I'm going to go ahead and close this issue. Please reach out if you have additional questions about the vocabulary reconstruction code/experiment.
