### ISSUE TITLE
Clarification on code for section 3.1 testing the robustness against different input formats

### ISSUE THREAD

**Issue by HuFY-dev** [ericwtodd/function_vectors#3]
I saw in section 3.1 and appendix B (Table 8) of your paper that you experimented different input format and tested the robustness. Did you do that by changing the `--prefixes` argument for `src/portability_eval.py`?

**Comment by ericwtodd** [comment]
The `--prefixes` argument in that file specifies the default template that is used to extract the function vectors. The other templates that are used as "test" templates (which we list in appendix B, table 8) are generated in the `portability_eval` function contained in `src/utils/eval_utils.py`. These test templates are used to override the `prefixes` and `separators` arguments during evaluation.
