### ISSUE TITLE
 Get the same clean_nll and intervention_nll when running n_shot_eval with compute_nll=True in eval_utils.py

### ISSUE THREAD

**Issue by xyVickyHu** [ericwtodd/function_vectors#9]
Thanks for the great work!

I get the same `clean_nll` and `intervention_nll` when I run `n_shot_eval` with `compute_nll=True` in `eval_utils.py`. 

I think it's because `intervention_fv` sets a wrong `idx` in `add_function_vector` for the case of `compute_nll=True` in `intervention_utils.py`. In this case, the input of the model is `nll_inputs`, which contains `target`. The intervention should no longer be applied to the last token of the model input (`nll_inputs`) as the other cases do, but to the last token of the original sentence (`inputs`).
https://github.com/ericwtodd/function_vectors/blob/54ec3bf343e338c27e81119f13f9df7752196f76/src/utils/intervention_utils.py#L164-L169

What I think should fix the bug is replacing 
```
intervention_fn = add_function_vector(edit_layer, function_vector.reshape(1, model_config['resid_dim']), model.device) 
```
by
```
    if compute_nll:
        idx = -1 - target_len
    else:
        idx = -1 
    intervention_fn = add_function_vector(edit_layer, function_vector.reshape(1, model_config['resid_dim']), model.device, idx=idx)
```

Does this make sense to you? Also it would be helpful if you could fix other codes possibly related to this bug. Thanks!

**Comment by ericwtodd** [comment]
Thanks for pointing out this bug! I have pushed some code that implements your suggested fix, I think that it should work. If you find any other discrepancies related to this, feel free to either re-open this issue, make a new issue, or submit a pull request. Thanks!
